app:
  version: 0.1.0

server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/suyuan?useSSL=false&serverTimezone=UTC&characterEncoding=utf8&allowPublicKeyRetrieval=true
    username: suyuan_app
    password: Suyuan@12345
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 5
      initialization-fail-timeout: 0
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        globally_quoted_identifiers: true

security:
  jwt:
    secret: change_me_to_a_long_random_secret_key_32_chars
    expiration-seconds: 7200
